-- shingo-camera Platform
-- Cloudflare D1 / SQLite initial schema
-- Status: Approved

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS M_USER (
    AUTH_USER_ID          TEXT PRIMARY KEY,
    LOGIN_MAIL            TEXT NOT NULL UNIQUE,
    STATUS                INTEGER NOT NULL DEFAULT 0,
    MAIL_AUTH_DATE        TEXT,
    PASSWORD_CHANGE_DATE  TEXT,
    LAST_LOGIN_DATE       TEXT,
    DEL_FLG               INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE           TEXT NOT NULL,
    UPDATE_DATE           TEXT NOT NULL,
    CHECK (STATUS IN (0, 1, 2, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS M_PRODUCT (
    PRODUCT_ID    INTEGER PRIMARY KEY,
    PRODUCT_CODE  TEXT NOT NULL UNIQUE,
    PRODUCT_NAME  TEXT NOT NULL,
    STATUS        INTEGER NOT NULL DEFAULT 1,
    SORT_NO       INTEGER NOT NULL DEFAULT 0,
    DEL_FLG       INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE   TEXT NOT NULL,
    UPDATE_DATE   TEXT NOT NULL,
    CHECK (STATUS IN (0, 1)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS M_SYSTEM_SETTING (
    SETTING_KEY    TEXT PRIMARY KEY,
    SETTING_VALUE  TEXT NOT NULL,
    DESCRIPTION    TEXT,
    UPDATE_DATE    TEXT NOT NULL
);

-- 注文ヘッダ（1回の決済）。WORK-011。
CREATE TABLE IF NOT EXISTS T_ORDER (
    ORDER_ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID       TEXT NOT NULL,
    PURCHASE_SOURCE    INTEGER NOT NULL,
    EXTERNAL_ORDER_ID  TEXT,
    ORDER_DATE         TEXT NOT NULL,
    TOTAL_AMOUNT       INTEGER NOT NULL DEFAULT 0,
    PAYMENT_STATUS     INTEGER NOT NULL DEFAULT 1,
    PAYMENT_INTENT_ID  TEXT,
    REFUND_DATE        TEXT,
    DEL_FLG            INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE        TEXT NOT NULL,
    UPDATE_DATE        TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    CHECK (PURCHASE_SOURCE IN (0, 1, 2)),
    CHECK (PAYMENT_STATUS IN (0, 1, 2, 3, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_T_ORDER_EXTERNAL
ON T_ORDER (PURCHASE_SOURCE, EXTERNAL_ORDER_ID)
WHERE EXTERNAL_ORDER_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_T_ORDER_USER_DATE
ON T_ORDER (AUTH_USER_ID, ORDER_DATE DESC);

CREATE TABLE IF NOT EXISTS T_PURCHASE (
    PURCHASE_ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID          TEXT NOT NULL,
    PRODUCT_ID            INTEGER NOT NULL,
    PURCHASE_SOURCE       INTEGER NOT NULL,
    EXTERNAL_PURCHASE_ID  TEXT,
    PURCHASE_DATE         TEXT NOT NULL,
    AMOUNT                INTEGER NOT NULL DEFAULT 0,
    PAYMENT_STATUS        INTEGER NOT NULL DEFAULT 1,
    REFUND_DATE           TEXT,
    ORDER_ID              INTEGER,
    DEL_FLG               INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE           TEXT NOT NULL,
    UPDATE_DATE           TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES T_ORDER (ORDER_ID),
    CHECK (PURCHASE_SOURCE IN (0, 1, 2)),
    CHECK (PAYMENT_STATUS IN (0, 1, 2, 3, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_T_PURCHASE_EXTERNAL
ON T_PURCHASE (PURCHASE_SOURCE, EXTERNAL_PURCHASE_ID)
WHERE EXTERNAL_PURCHASE_ID IS NOT NULL;

CREATE INDEX IF NOT EXISTS IX_T_PURCHASE_ORDER
ON T_PURCHASE (ORDER_ID);

CREATE UNIQUE INDEX IF NOT EXISTS UX_T_PURCHASE_ORDER_PRODUCT
ON T_PURCHASE (ORDER_ID, PRODUCT_ID)
WHERE ORDER_ID IS NOT NULL;

CREATE TABLE IF NOT EXISTS T_USER_PRODUCT (
    AUTH_USER_ID  TEXT NOT NULL,
    PRODUCT_ID    INTEGER NOT NULL,
    STATUS        INTEGER NOT NULL DEFAULT 1,
    START_DATE    TEXT NOT NULL,
    END_DATE      TEXT NOT NULL DEFAULT '9999-12-31T23:59:59+09:00',
    GRANT_TYPE    INTEGER NOT NULL,
    PURCHASE_ID   INTEGER,
    MEMO          TEXT,
    DEL_FLG       INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE   TEXT NOT NULL,
    UPDATE_DATE   TEXT NOT NULL,
    PRIMARY KEY (AUTH_USER_ID, PRODUCT_ID),
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    FOREIGN KEY (PURCHASE_ID) REFERENCES T_PURCHASE (PURCHASE_ID),
    CHECK (STATUS IN (0, 1, 2, 9)),
    CHECK (GRANT_TYPE IN (0, 1, 2, 3, 4)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS T_NOTE_PURCHASE (
    NOTE_PURCHASE_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID           INTEGER NOT NULL,
    NOTE_ID              TEXT,
    NOTE_TRANSACTION_ID  TEXT NOT NULL UNIQUE,
    PURCHASE_DATE        TEXT NOT NULL,
    PURCHASE_AMOUNT      INTEGER NOT NULL DEFAULT 0,
    MATCH_STATUS         INTEGER NOT NULL DEFAULT 0,
    MATCH_AUTH_USER_ID   TEXT,
    MATCH_DATE           TEXT,
    PURCHASE_ID          INTEGER,
    DEL_FLG              INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE          TEXT NOT NULL,
    UPDATE_DATE          TEXT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    FOREIGN KEY (MATCH_AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PURCHASE_ID) REFERENCES T_PURCHASE (PURCHASE_ID),
    CHECK (MATCH_STATUS IN (0, 1, 2, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS T_LOGIN_LOG (
    LOGIN_LOG_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID    TEXT,
    LOGIN_DATE      TEXT NOT NULL,
    LOGIN_RESULT    INTEGER NOT NULL,
    IP_ADDRESS      TEXT,
    COUNTRY_CODE    TEXT,
    REGION          TEXT,
    CITY            TEXT,
    DEVICE_ID       TEXT,
    USER_AGENT      TEXT,
    OS_NAME         TEXT,
    BROWSER_NAME    TEXT,
    FAILURE_REASON  TEXT,
    CREATE_DATE     TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    CHECK (LOGIN_RESULT IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS T_ACCESS_LOG (
    ACCESS_LOG_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID     TEXT NOT NULL,
    PRODUCT_ID       INTEGER NOT NULL,
    ACCESS_DATE      TEXT NOT NULL,
    ACCESS_TYPE      INTEGER NOT NULL,
    IP_ADDRESS       TEXT,
    COUNTRY_CODE     TEXT,
    REGION           TEXT,
    CITY             TEXT,
    DEVICE_ID        TEXT,
    USER_AGENT       TEXT,
    OS_NAME          TEXT,
    BROWSER_NAME     TEXT,
    SESSION_ID_HASH  TEXT,
    CREATE_DATE      TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    CHECK (ACCESS_TYPE IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS T_WARNING (
    WARNING_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID      TEXT NOT NULL,
    PRODUCT_ID        INTEGER,
    WARNING_TYPE      TEXT NOT NULL,
    WARNING_SCORE     INTEGER NOT NULL,
    DETECT_DATE       TEXT NOT NULL,
    PERIOD_START      TEXT,
    PERIOD_END        TEXT,
    NOTIFIED_DATE     TEXT,
    STATUS            INTEGER NOT NULL DEFAULT 0,
    LAST_ACTION_DATE  TEXT,
    MEMO              TEXT,
    CREATE_DATE       TEXT NOT NULL,
    UPDATE_DATE       TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    CHECK (STATUS IN (0, 1, 2, 9))
);

CREATE INDEX IF NOT EXISTS IX_T_USER_PRODUCT_PRODUCT
ON T_USER_PRODUCT (PRODUCT_ID, STATUS, DEL_FLG);

CREATE INDEX IF NOT EXISTS IX_T_PURCHASE_USER_DATE
ON T_PURCHASE (AUTH_USER_ID, PURCHASE_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_NOTE_PURCHASE_NOTE_ID
ON T_NOTE_PURCHASE (NOTE_ID);

CREATE INDEX IF NOT EXISTS IX_T_NOTE_PURCHASE_MATCH
ON T_NOTE_PURCHASE (MATCH_STATUS, PRODUCT_ID);

CREATE INDEX IF NOT EXISTS IX_T_LOGIN_LOG_USER_DATE
ON T_LOGIN_LOG (AUTH_USER_ID, LOGIN_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_ACCESS_LOG_USER_DATE
ON T_ACCESS_LOG (AUTH_USER_ID, ACCESS_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_ACCESS_LOG_WARNING
ON T_ACCESS_LOG (ACCESS_DATE DESC, AUTH_USER_ID, DEVICE_ID, REGION);

CREATE INDEX IF NOT EXISTS IX_T_WARNING_STATUS_DATE
ON T_WARNING (STATUS, DETECT_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_WARNING_USER_DATE
ON T_WARNING (AUTH_USER_ID, DETECT_DATE DESC);

-- ============================================================
-- 支払い試行層（WORK-011 / migration 0006）。
-- Stripe Checkout Session を「支払い試行」として追跡し、二重課金の事前防止
-- （DB 制約による並行 Checkout 排他）・HTTP 再送収束・paid 未反映の救済・
-- refund/dispute 追跡の土台とする。追加型のみ・既存データ非破壊。Stripe 専用
-- （note 移行は通らない）。
-- ============================================================

-- T_CHECKOUT_ATTEMPT（支払い試行ヘッダ：1 行 = 1 回の Checkout 試行 ≒ 1 Stripe Session）
CREATE TABLE IF NOT EXISTS T_CHECKOUT_ATTEMPT (
    ATTEMPT_ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    OPERATION_ID       TEXT NOT NULL,               -- browser 生成の安定キー（HTTP 再送収束・idempotency の基）
    AUTH_USER_ID       TEXT NOT NULL,               -- 検証済み sub（購入者）
    CART_KEY           TEXT NOT NULL,               -- server 正規化した商品構成の安定表現（同一試行判定）
    BUYER_EMAIL        TEXT NOT NULL,               -- attempt 開始時の認証 email スナップショット（retry でも不変）
    STATUS             INTEGER NOT NULL DEFAULT 0,  -- 0=CREATING,1=OPEN,2=PAID,3=EXPIRED,4=CANCELLED
    CREATE_ATTEMPTED   INTEGER NOT NULL DEFAULT 0,  -- Stripe create を呼ぶ直前に 1 を確定（0+SID=NULL=未試行 / 1+SID=NULL=結果不明）
    STRIPE_SESSION_ID  TEXT,                        -- Stripe 作成後にセット（作成前は NULL）
    TOTAL_AMOUNT       INTEGER NOT NULL DEFAULT 0,  -- 期待合計（表示・照合補助。正本は Webhook 再取得値）
    EXPIRES_AT         TEXT,                        -- Stripe Session の expires_at（JST ISO）
    DEL_FLG            INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE        TEXT NOT NULL,
    UPDATE_DATE        TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    CHECK (STATUS IN (0, 1, 2, 3, 4)),
    CHECK (DEL_FLG IN (0, 1))
);

-- 同一 operationId の HTTP 再送を同一 attempt 行へ収束させる（idempotency の DB 保証）。
CREATE UNIQUE INDEX IF NOT EXISTS UX_ATTEMPT_OPERATION
ON T_CHECKOUT_ATTEMPT (OPERATION_ID);

-- 同一 Stripe Session を二重に試行記録しない（NULL は対象外の部分 UNIQUE）。
CREATE UNIQUE INDEX IF NOT EXISTS UX_ATTEMPT_SESSION
ON T_CHECKOUT_ATTEMPT (STRIPE_SESSION_ID)
WHERE STRIPE_SESSION_ID IS NOT NULL;

-- ユーザー×状態での追跡（active 試行の探索・管理画面）。
CREATE INDEX IF NOT EXISTS IX_ATTEMPT_USER_STATUS
ON T_CHECKOUT_ATTEMPT (AUTH_USER_ID, STATUS);

-- T_CHECKOUT_ATTEMPT_ITEM（試行で確定した immutable 商品/Price スナップショット）
CREATE TABLE IF NOT EXISTS T_CHECKOUT_ATTEMPT_ITEM (
    ATTEMPT_ITEM_ID  INTEGER PRIMARY KEY AUTOINCREMENT,
    ATTEMPT_ID       INTEGER NOT NULL,              -- T_CHECKOUT_ATTEMPT への参照
    PRODUCT_ID       INTEGER NOT NULL,              -- 付与対象（内部 ID）
    PRODUCT_CODE     TEXT NOT NULL,                 -- 監査・CART_KEY・metadata 用
    STRIPE_PRICE_ID  TEXT NOT NULL,                 -- create 再実行で使う price（attempt 時点で固定）
    EXPECTED_AMOUNT  INTEGER NOT NULL,              -- 将来の監査用予約列（試行時点の期待額）。現行フローでは未使用・0 を許容。金額正本は Stripe 側
    SORT_NO          INTEGER NOT NULL,              -- line_items の安定順序（create 再現の決定性）
    CREATE_DATE      TEXT NOT NULL,
    FOREIGN KEY (ATTEMPT_ID) REFERENCES T_CHECKOUT_ATTEMPT (ATTEMPT_ID)
);

CREATE INDEX IF NOT EXISTS IX_ATTEMPT_ITEM_ATTEMPT
ON T_CHECKOUT_ATTEMPT_ITEM (ATTEMPT_ID);

-- 同一試行内での同一商品の重複を防止。
CREATE UNIQUE INDEX IF NOT EXISTS UX_ATTEMPT_ITEM_PRODUCT
ON T_CHECKOUT_ATTEMPT_ITEM (ATTEMPT_ID, PRODUCT_ID);

-- T_PRODUCT_CHECKOUT_LOCK（active な同一商品購入の競合防止・行の存在=active 予約）
-- PRIMARY KEY(AUTH_USER_ID, PRODUCT_ID) が並行 Checkout 排他の正本。
CREATE TABLE IF NOT EXISTS T_PRODUCT_CHECKOUT_LOCK (
    AUTH_USER_ID TEXT NOT NULL,
    PRODUCT_ID   INTEGER NOT NULL,
    ATTEMPT_ID   INTEGER NOT NULL,                  -- どの試行が押さえているか（解放・stale 掃除用）
    CREATE_DATE  TEXT NOT NULL,
    PRIMARY KEY (AUTH_USER_ID, PRODUCT_ID),         -- 同一ユーザー・同一商品の active 予約は最大 1
    FOREIGN KEY (ATTEMPT_ID) REFERENCES T_CHECKOUT_ATTEMPT (ATTEMPT_ID)
);

-- 試行単位での lock 解放（attempt 完了/expire/cancel 時）。
CREATE INDEX IF NOT EXISTS IX_LOCK_ATTEMPT
ON T_PRODUCT_CHECKOUT_LOCK (ATTEMPT_ID);

-- T_PAYMENT_EVENT（決済運用イベント記録：duplicate paid / refund / dispute /
--   fulfill failure / reconcile / server indeterminate）。
--   既存 4 種の不正利用 warning（T_WARNING）とは意味が異なるため分離する。
CREATE TABLE IF NOT EXISTS T_PAYMENT_EVENT (
    PAYMENT_EVENT_ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_TYPE         INTEGER NOT NULL,            -- 1=DUPLICATE_PAID,2=REFUND,3=DISPUTE,4=FULFILL_FAILURE,5=RECONCILE,6=SERVER_INDETERMINATE
    AUTH_USER_ID       TEXT,
    ORDER_ID           INTEGER,                     -- 該当注文（あれば）
    STRIPE_SESSION_ID  TEXT,
    PAYMENT_INTENT_ID  TEXT,
    STRIPE_OBJECT_ID   TEXT,                        -- refund id / dispute id 等
    STRIPE_EVENT_ID    TEXT,                        -- Webhook event.id（冪等キー）
    STRIPE_REQUEST_ID  TEXT,                        -- 調査用（可能なら保存）
    STATUS             TEXT,                        -- refund/dispute の status 文字列
    AMOUNT             INTEGER,
    DETAIL             TEXT,                        -- reason 等（機微情報・カード情報は入れない）
    NOTIFIED_DATE      TEXT,                        -- 管理者通知済み時刻
    DEL_FLG            INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE        TEXT NOT NULL,
    UPDATE_DATE        TEXT NOT NULL,
    CHECK (EVENT_TYPE IN (1, 2, 3, 4, 5, 6)),
    CHECK (DEL_FLG IN (0, 1))
);

-- refund/dispute の Webhook 再送で同じ event を二重記録しない（NULL は対象外）。
CREATE UNIQUE INDEX IF NOT EXISTS UX_PAYEVENT_STRIPE_EVENT
ON T_PAYMENT_EVENT (STRIPE_EVENT_ID)
WHERE STRIPE_EVENT_ID IS NOT NULL;

-- 注文・種別での追跡。
CREATE INDEX IF NOT EXISTS IX_PAYEVENT_ORDER
ON T_PAYMENT_EVENT (ORDER_ID);
CREATE INDEX IF NOT EXISTS IX_PAYEVENT_TYPE_DATE
ON T_PAYMENT_EVENT (EVENT_TYPE, CREATE_DATE DESC);

-- T_ORDER.PAYMENT_INTENT_ID（refund/dispute イベントから注文を逆引き）は
-- 上部 T_ORDER 定義に統合済み（migration 0006 の ADD COLUMN 相当）。
CREATE INDEX IF NOT EXISTS IX_T_ORDER_PI
ON T_ORDER (PAYMENT_INTENT_ID);

INSERT OR IGNORE INTO M_PRODUCT
    (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, STATUS, SORT_NO, DEL_FLG, CREATE_DATE, UPDATE_DATE)
VALUES
    (1, 'SUN_AND_MOON', 'SUN AND MOON PLANNER', 1, 10, 0, strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    (2, 'HANABI', 'HANABI PLANNER', 1, 20, 0, strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    (3, 'HANABI_GOOGLE_EARTH', 'HANABI PLANNER Google Earth追加機能', 1, 30, 0, strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00');

INSERT OR IGNORE INTO M_SYSTEM_SETTING
    (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATE_DATE)
VALUES
    ('WARNING_SCORE', '100', '管理者メール通知を行うWarningスコア', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('LOGIN_FAIL_LIMIT', '5', '一定期間内のログイン失敗回数の初期閾値', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('ACCESS_LOG_KEEP_DAYS', '180', 'アクセスログ保持日数の目安', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('WARNING_MAIL_INTERVAL_MIN', '60', '同一対象へのWarning通知抑止時間（分）', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('DEVICE_CHANGE_SCORE', '10', '端末変化時の初期スコア', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('REGION_CHANGE_SCORE', '20', '地域変化時の初期スコア', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('COUNTRY_CHANGE_SCORE', '50', '国変化時の初期スコア', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00'),
    ('ACCESS_LOG_INTERVAL_MIN', '60', '権限確認アクセスログの最小記録間隔（分）', strftime('%Y-%m-%dT%H:%M:%S','now','+9 hours') || '+09:00');
