-- shingo-camera Platform
-- Cloudflare D1 / SQLite initial schema
-- Status: Approved

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS M_USER (
    AUTH_USER_ID          TEXT PRIMARY KEY,
    LOGIN_MAIL            TEXT NOT NULL UNIQUE,
    STATUS                INTEGER NOT NULL DEFAULT 0,
    MAIL_AUTH_DATE        TEXT,
    PASSWORD_CHANGE_DATE  TEXT,
    LAST_LOGIN_DATE       TEXT,
    DEL_FLG               INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE           TEXT NOT NULL,
    UPDATE_DATE           TEXT NOT NULL,
    CHECK (STATUS IN (0, 1, 2, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS M_PRODUCT (
    PRODUCT_ID    INTEGER PRIMARY KEY,
    PRODUCT_CODE  TEXT NOT NULL UNIQUE,
    PRODUCT_NAME  TEXT NOT NULL,
    STATUS        INTEGER NOT NULL DEFAULT 1,
    SORT_NO       INTEGER NOT NULL DEFAULT 0,
    DEL_FLG       INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE   TEXT NOT NULL,
    UPDATE_DATE   TEXT NOT NULL,
    CHECK (STATUS IN (0, 1)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS M_SYSTEM_SETTING (
    SETTING_KEY    TEXT PRIMARY KEY,
    SETTING_VALUE  TEXT NOT NULL,
    DESCRIPTION    TEXT,
    UPDATE_DATE    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS T_PURCHASE (
    PURCHASE_ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID          TEXT NOT NULL,
    PRODUCT_ID            INTEGER NOT NULL,
    PURCHASE_SOURCE       INTEGER NOT NULL,
    EXTERNAL_PURCHASE_ID  TEXT,
    PURCHASE_DATE         TEXT NOT NULL,
    AMOUNT                INTEGER NOT NULL DEFAULT 0,
    PAYMENT_STATUS        INTEGER NOT NULL DEFAULT 1,
    REFUND_DATE           TEXT,
    DEL_FLG               INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE           TEXT NOT NULL,
    UPDATE_DATE           TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    CHECK (PURCHASE_SOURCE IN (0, 1, 2)),
    CHECK (PAYMENT_STATUS IN (0, 1, 2, 3, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS UX_T_PURCHASE_EXTERNAL
ON T_PURCHASE (PURCHASE_SOURCE, EXTERNAL_PURCHASE_ID)
WHERE EXTERNAL_PURCHASE_ID IS NOT NULL;

CREATE TABLE IF NOT EXISTS T_USER_PRODUCT (
    AUTH_USER_ID  TEXT NOT NULL,
    PRODUCT_ID    INTEGER NOT NULL,
    STATUS        INTEGER NOT NULL DEFAULT 1,
    START_DATE    TEXT NOT NULL,
    END_DATE      TEXT NOT NULL DEFAULT '9999-12-31T23:59:59+09:00',
    GRANT_TYPE    INTEGER NOT NULL,
    PURCHASE_ID   INTEGER,
    MEMO          TEXT,
    DEL_FLG       INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE   TEXT NOT NULL,
    UPDATE_DATE   TEXT NOT NULL,
    PRIMARY KEY (AUTH_USER_ID, PRODUCT_ID),
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    FOREIGN KEY (PURCHASE_ID) REFERENCES T_PURCHASE (PURCHASE_ID),
    CHECK (STATUS IN (0, 1, 2, 9)),
    CHECK (GRANT_TYPE IN (0, 1, 2, 3, 4)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS T_NOTE_PURCHASE (
    NOTE_PURCHASE_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCT_ID           INTEGER NOT NULL,
    NOTE_ID              TEXT,
    NOTE_TRANSACTION_ID  TEXT NOT NULL UNIQUE,
    PURCHASE_DATE        TEXT NOT NULL,
    PURCHASE_AMOUNT      INTEGER NOT NULL DEFAULT 0,
    MATCH_STATUS         INTEGER NOT NULL DEFAULT 0,
    MATCH_AUTH_USER_ID   TEXT,
    MATCH_DATE           TEXT,
    PURCHASE_ID          INTEGER,
    DEL_FLG              INTEGER NOT NULL DEFAULT 0,
    CREATE_DATE          TEXT NOT NULL,
    UPDATE_DATE          TEXT NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    FOREIGN KEY (MATCH_AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PURCHASE_ID) REFERENCES T_PURCHASE (PURCHASE_ID),
    CHECK (MATCH_STATUS IN (0, 1, 2, 9)),
    CHECK (DEL_FLG IN (0, 1))
);

CREATE TABLE IF NOT EXISTS T_LOGIN_LOG (
    LOGIN_LOG_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID    TEXT,
    LOGIN_DATE      TEXT NOT NULL,
    LOGIN_RESULT    INTEGER NOT NULL,
    IP_ADDRESS      TEXT,
    COUNTRY_CODE    TEXT,
    REGION          TEXT,
    CITY            TEXT,
    DEVICE_ID       TEXT,
    USER_AGENT      TEXT,
    OS_NAME         TEXT,
    BROWSER_NAME    TEXT,
    FAILURE_REASON  TEXT,
    CREATE_DATE     TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    CHECK (LOGIN_RESULT IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS T_ACCESS_LOG (
    ACCESS_LOG_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID     TEXT NOT NULL,
    PRODUCT_ID       INTEGER NOT NULL,
    ACCESS_DATE      TEXT NOT NULL,
    ACCESS_TYPE      INTEGER NOT NULL,
    IP_ADDRESS       TEXT,
    COUNTRY_CODE     TEXT,
    REGION           TEXT,
    CITY             TEXT,
    DEVICE_ID        TEXT,
    USER_AGENT       TEXT,
    OS_NAME          TEXT,
    BROWSER_NAME     TEXT,
    SESSION_ID_HASH  TEXT,
    CREATE_DATE      TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    CHECK (ACCESS_TYPE IN (0, 1, 2))
);

CREATE TABLE IF NOT EXISTS T_WARNING (
    WARNING_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    AUTH_USER_ID      TEXT NOT NULL,
    PRODUCT_ID        INTEGER,
    WARNING_TYPE      TEXT NOT NULL,
    WARNING_SCORE     INTEGER NOT NULL,
    DETECT_DATE       TEXT NOT NULL,
    PERIOD_START      TEXT,
    PERIOD_END        TEXT,
    NOTIFIED_DATE     TEXT,
    STATUS            INTEGER NOT NULL DEFAULT 0,
    LAST_ACTION_DATE  TEXT,
    MEMO              TEXT,
    CREATE_DATE       TEXT NOT NULL,
    UPDATE_DATE       TEXT NOT NULL,
    FOREIGN KEY (AUTH_USER_ID) REFERENCES M_USER (AUTH_USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES M_PRODUCT (PRODUCT_ID),
    CHECK (STATUS IN (0, 1, 2, 9))
);

CREATE INDEX IF NOT EXISTS IX_T_USER_PRODUCT_PRODUCT
ON T_USER_PRODUCT (PRODUCT_ID, STATUS, DEL_FLG);

CREATE INDEX IF NOT EXISTS IX_T_PURCHASE_USER_DATE
ON T_PURCHASE (AUTH_USER_ID, PURCHASE_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_NOTE_PURCHASE_NOTE_ID
ON T_NOTE_PURCHASE (NOTE_ID);

CREATE INDEX IF NOT EXISTS IX_T_NOTE_PURCHASE_MATCH
ON T_NOTE_PURCHASE (MATCH_STATUS, PRODUCT_ID);

CREATE INDEX IF NOT EXISTS IX_T_LOGIN_LOG_USER_DATE
ON T_LOGIN_LOG (AUTH_USER_ID, LOGIN_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_ACCESS_LOG_USER_DATE
ON T_ACCESS_LOG (AUTH_USER_ID, ACCESS_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_ACCESS_LOG_WARNING
ON T_ACCESS_LOG (ACCESS_DATE DESC, AUTH_USER_ID, DEVICE_ID, REGION);

CREATE INDEX IF NOT EXISTS IX_T_WARNING_STATUS_DATE
ON T_WARNING (STATUS, DETECT_DATE DESC);

CREATE INDEX IF NOT EXISTS IX_T_WARNING_USER_DATE
ON T_WARNING (AUTH_USER_ID, DETECT_DATE DESC);

INSERT OR IGNORE INTO M_PRODUCT
    (PRODUCT_ID, PRODUCT_CODE, PRODUCT_NAME, STATUS, SORT_NO, DEL_FLG, CREATE_DATE, UPDATE_DATE)
VALUES
    (1, 'SUN_AND_MOON', 'SUN AND MOON PLANNER', 1, 10, 0, datetime('now'), datetime('now')),
    (2, 'HANABI', 'HANABI PLANNER', 1, 20, 0, datetime('now'), datetime('now')),
    (3, 'HANABI_GOOGLE_EARTH', 'HANABI PLANNER Google Earth追加機能', 1, 30, 0, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO M_SYSTEM_SETTING
    (SETTING_KEY, SETTING_VALUE, DESCRIPTION, UPDATE_DATE)
VALUES
    ('WARNING_SCORE', '100', '管理者メール通知を行うWarningスコア', datetime('now')),
    ('LOGIN_FAIL_LIMIT', '5', '一定期間内のログイン失敗回数の初期閾値', datetime('now')),
    ('ACCESS_LOG_KEEP_DAYS', '180', 'アクセスログ保持日数の目安', datetime('now')),
    ('WARNING_MAIL_INTERVAL_MIN', '60', '同一対象へのWarning通知抑止時間（分）', datetime('now')),
    ('DEVICE_CHANGE_SCORE', '10', '端末変化時の初期スコア', datetime('now')),
    ('REGION_CHANGE_SCORE', '20', '地域変化時の初期スコア', datetime('now')),
    ('COUNTRY_CHANGE_SCORE', '50', '国変化時の初期スコア', datetime('now'));
